# Generated by Django 6.0.3 on 2026-03-13 04:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("page", "Page"),
                            ("page-spa", "Page SPA"),
                            ("prefix", "Prefix"),
                            ("host", "Host"),
                            ("domain", "Domain"),
                            ("any", "Any"),
                            ("custom", "Custom"),
                        ],
                        default="page",
                        max_length=20,
                        verbose_name="Crawl Scope",
                    ),
                ),
                (
                    "include",
                    models.TextField(
                        blank=True, null=True, verbose_name="Include Rule Regex"
                    ),
                ),
                (
                    "extra_hops",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Number of extra hops beyond scope",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawls",
                        to="crawler.crawlconfiguration",
                        verbose_name="Configuration",
                    ),
                ),
            ],
        ),
    ]
