# Generated by Django 6.0.3 on 2026-03-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawl",
            name="container_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Docker Container ID",
            ),
        ),
        migrations.AddField(
            model_name="crawl",
            name="wacz_archive",
            field=models.FileField(
                blank=True, null=True, upload_to="waczs/", verbose_name="WACZ Archive"
            ),
        ),
    ]
