# Generated by Django 6.0.3 on 2026-03-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0002_crawl_container_id_crawl_wacz_archive"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crawl",
            options={"ordering": ["-created_at"]},
        ),
    ]
