# Generated by Django 6.0.3 on 2026-03-13 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0003_alter_crawl_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawl",
            name="wacz_file_size",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="WACZ File Size",
            ),
        ),
    ]
