# Generated by Django 6.0.3 on 2026-03-13 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0004_crawl_wacz_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlconfiguration",
            name="allow_hash_urls",
            field=models.BooleanField(default=False, verbose_name="Allow Hash URLs"),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="behavior_timeout",
            field=models.IntegerField(default=90, verbose_name="Behavior Timeout"),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="block_ads",
            field=models.BooleanField(default=False, verbose_name="Block Ads"),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="lang",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Language Code"
            ),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="max_page_retries",
            field=models.IntegerField(default=2, verbose_name="Max Page Retries"),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="page_limit",
            field=models.IntegerField(default=0, verbose_name="Page Limit"),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="page_load_timeout",
            field=models.IntegerField(default=90, verbose_name="Page Load Timeout"),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="screenshots",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "-"),
                    ("view", "View"),
                    ("fullPage", "Full Page"),
                    ("thumbnail", "Thumbnail"),
                ],
                max_length=20,
                null=True,
                verbose_name="Screenshots",
            ),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="size_limit",
            field=models.IntegerField(default=0, verbose_name="Size Limit"),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="text_extract",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "-"),
                    ("to-pages", "to pages"),
                    ("to-warc", "to WARC"),
                    ("final-to-warc", "final to WARC"),
                ],
                max_length=20,
                null=True,
                verbose_name="Text Extraction",
            ),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="time_limit",
            field=models.IntegerField(default=0, verbose_name="Time Limit"),
        ),
        migrations.AddField(
            model_name="crawlconfiguration",
            name="workers",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Workers",
            ),
        ),
    ]
