# Generated by Django 6.0.3 on 2026-03-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0006_browserprofile_crawlconfiguration_browser_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawl",
            name="screenshot",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="wacz-screenshots/",
                verbose_name="Screenshot",
            ),
        ),
    ]
